// swift-tools-version: 5.6

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "CoverFlow",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "CoverFlow",
            targets: ["AppModule"],
            bundleIdentifier: "com.yongfrank.CoverFlow",
            teamIdentifier: "L3P8YP4XRH",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .coffee),
            accentColor: .presetColor(.purple),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ]
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
        //                .enableUpcomingFeature("BareSlashRegexLiterals")
                .unsafeFlags(["-enable-bare-slash-regex"])
            ]
        )
    ]
)
