// swift-tools-version: 5.7

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Regex Go",
    platforms: [
        .iOS("16.0")
    ],
    products: [
        .iOSApplication(
            name: "Regex Go",
            targets: ["AppModule"],
            bundleIdentifier: "com.yongfrank.RegexGo",
            teamIdentifier: "L3P8YP4XRH",
            displayVersion: "1.0",
            bundleVersion: "5",
            appIcon: .asset("AppIcon"),
            accentColor: .presetColor(.orange),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .utilities
        )
    ],
    dependencies: [
        .package(url: "https://github.com/FLEXTool/FLEX.git", "5.0.0"..<"6.0.0")
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            dependencies: [
                .product(name: "FLEX", package: "flex")
            ],
            path: ".",
            resources: [
                .process("Resources")
            ],
            swiftSettings: [
                .unsafeFlags(["-enable-bare-slash-regex"])
            ]
        )
    ]
)